mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_new
train_data_path: data/mt_new/new_train
train_batch_size: 1024
valid_data_path: data/mt_new/new_val
valid_batch_size: 1024
test_data_path: data/mt_new/new_test
test_batch_size: 1024

aug_path: /home/hadoop-aipnlp/dolphinfs/qinlijiao02/LM+GNN/data/mt/augment_expose_min_limit_50_pos_min_ctr_limit_0.05_neg_max_ctr_limit_0

n_epoch: 1000
model: bert
early_stop: 4
bert_hidden_size: 384
num_classes: 2
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
main_metric: f1
random_seed: 666

optimizer_params:
  lr: 0.00001
  correct_bias: False


