mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_intent_yj
train_dataset: 
  name: intent
  params:
    data_path: data/intent/train.txt
train_data_collator:
  name: intent_yj
  params:
    query_path: data/intent_yuji/404_1734_11226.query
train_batch_size: 1024


val_dataset: 
  name: intent
  params:
    data_path: data/intent/val.txt
val_data_collator:
  name: intent_yj
  params:
    query_path: data/intent_yuji/404_1734_11226.query
valid_batch_size: 1024

test_dataset: 
  name: intent
  params:
    data_path: data/intent/test.txt
test_data_collator:
  name: intent_yj
  params:
    query_path: data/intent_yuji/404_1734_11226.query
test_batch_size: 1024

# for dist
find_unused_parameters: False

model_params:
  emb_path: data/intent_yuji/404_1734_11226.query.npy
  emb_freeze: True
  num_classes: 388

#############
n_epoch: 1000
model: simple_cls
early_stop: 10
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
eval_func: eval_multi_class
main_metric: f1
random_seed: 666

optimizer: adam
optimizer_params:
  lr: 1e-3

description: 404_1734_11226


