mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_aug
train_dataset: 
  name: bert
  params:
    data_path: data/mt_aug/aug_rand_neg_train.txt
    aug: null
    aug_path: null
train_data_collator:
  name: bert_pretrain
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
    mlm_probability: 0.15
train_batch_size: 1024


val_dataset: 
  name: bert
  params:
    data_path: data/mt_aug/aug_rand_neg_val.txt
    aug: null
    aug_path: null
val_data_collator:
  name: bert_pretrain
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
    mlm_probability: 0.15
valid_batch_size: 1024

test_dataset: null
test_data_collator: null
test_batch_size: 1024

# for dist
find_unused_parameters: False

#############
n_epoch: 1000
model: bert_pretrain
early_stop: 4
bert_hidden_size: 384
num_classes: 2
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
eval_func: eval_loss
main_metric: loss
random_seed: 666

optimizer_params:
  lr: 0.00001
  correct_bias: False


