mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_new
train_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_train
    soft_label_path: null
train_data_collator:
  name: sbert_png
  params:
    dataset_path: data/mt_new
    g_path: data/mt_new/pos_neg_train.graph
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
    fanouts: [5]
    pos_sample: True
    neg_sample: True
train_batch_size: 128


val_dataset: 
  name: bert
  params:
    data_path: data/mt_new/new_val
    aug: null
    aug_path: null
val_data_collator:
  name: sbert
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
valid_batch_size: 1024

test_dataset: 
  name: bert
  params:
    data_path: data/mt_new/new_test
    aug: null
    aug_path: null
test_data_collator:
  name: sbert
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
test_batch_size: 1024

model_params:
  bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
  gnn: gcn
  gnn_emb: 384
  gnn_layers: 1
  png_loss_lambda: 0.2
  num_classes: 2

####for dist#######
find_unused_parameters: True

#######distill#######
hard_label_lambda: 1

#############
n_epoch: 1000
model: sbert_png
early_stop: 10
bert_hidden_size: 384
num_classes: 2
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
main_metric: f1
random_seed: 666
optimizer_func: optimizer_bert

optimizer_params:
  lr: 0.00001
  correct_bias: False

scheduler_params:
  scheduler: WarmupLinear
  warmup_steps: 0.05


