#####gnn接在bert之后##########
mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_new
train_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_train
    soft_label_path: null
train_data_collator:
  name: sbert_gnn2
  params:
    dataset_path: data/mt_new
    g_path: data/mt_new/pos_neg_train.graph
    fanouts: [5]
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
    is_train: True
train_batch_size: 128


val_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_val
    soft_label_path: null
val_data_collator:
  name: sbert_gnn2
  params:
    dataset_path: data/mt_new
    g_path: data/mt_new/pos_neg_train.graph
    fanouts: [5]
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
    is_train: False
valid_batch_size: 1024

test_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_test
    soft_label_path: null
test_data_collator:
  name: sbert_gnn2
  params:
    dataset_path: data/mt_new
    g_path: data/mt_new/pos_neg_train.graph
    fanouts: [5]
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
    is_train: False
test_batch_size: 1024

model_params:
  bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
  gnn_emb: 384
  gnn_layers: 1
  num_classes: 2
  gnn: gcn
  infonce_lambda: 0.1
  temp: 0.05

description: infonce
####for dist#######
find_unused_parameters: True


#############
n_epoch: 1000
model: sbert_gnn2
early_stop: 10
bert_hidden_size: 384
num_classes: 2
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
main_metric: f1
random_seed: 666
optimizer_func: optimizer_bert

optimizer_params:
  lr: 0.00001
  correct_bias: False

scheduler_params:
  scheduler: WarmupLinear
  warmup_steps: 0.05


