mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_new
train_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_train
    soft_label_path: null
train_data_collator:
  name: sbert_distill_ncl
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
train_batch_size: 512


val_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_val
    soft_label_path: null
val_data_collator:
  name: sbert_distill_ncl
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
valid_batch_size: 512

test_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_new/new_test
    soft_label_path: null
test_data_collator:
  name: sbert_distill_ncl
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
    query_path: data/mt_new/queries
    spu_path: data/mt_new/spus
test_batch_size: 512

model_params:
  bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
  num_classes: 2
  hard_label_lambda: 1
  ncl_params:
    embedding_size: 64
    n_layers: 3
    reg_weight: 1e-4
    ssl_temp: 0.1
    ssl_reg: 1e-7
    hyper_layers: 1

    alpha: 1

    proto_reg: 8e-8
    num_clusters: 1000

    m_step: 1
    warm_up_step: 20
    graph_path: data/mt_new/q_s_train.graph
    n_users: 218758
    n_items: 1678075

####for dist#######
find_unused_parameters: True


#############
n_epoch: 1000
model: sbert_distill_ncl
early_stop: 10
bert_hidden_size: 384
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
main_metric: f1
random_seed: 666
optimizer_func: optimizer_bert

optimizer_params:
  lr: 0.00001
  correct_bias: False

scheduler_params:
  scheduler: WarmupLinear
  warmup_steps: 0.05


