mode: train

bert_path: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/

dataset: mt_aug
train_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_aug/aug_rand_neg_train.txt
    soft_label_path: ckpt/mt_aug/bert_2022-12-22_14:47:18/train_logits.npy
train_data_collator:
  name: sbert_distill
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
train_batch_size: 1024


val_dataset: 
  name: sbert_distill
  params:
    data_path: data/mt_aug/aug_rand_neg_val.txt
    soft_label_path: ckpt/mt_aug/bert_2022-12-22_14:54:28/val_logits.npy
val_data_collator:
  name: sbert_distill
  params:
    token_length: 32
    tokenizer: /mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/yangyang113/distillation_clean/plms/smallbert_yuji/auto-medium/
valid_batch_size: 1024

test_dataset: null
test_batch_size: 1024

####for dist#######
find_unused_parameters: True

#######distill#######
hard_label_lambda: 0.5

#############
n_epoch: 1000
model: sbert_distill
early_stop: 4
bert_hidden_size: 384
num_classes: 2
max_length: 32
print_every: 50
save_every_epoch: 5
eval_every_epoch: 1
eval_func: eval_loss
main_metric: loss
random_seed: 666

optimizer_params:
  lr: 0.00001
  correct_bias: False

scheduler_params:
  scheduler: WarmupLinear
  warmup_steps: 0.05


